name: CI for Node Package

on: [ push ]
jobs:
  build:
    name: Build, lint, and test on ${{ matrix.os }} and finally Release

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Install deps and build (with cache)
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Release
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
