name: CI/CD for package test && release

on:
  push:
    branches: [ 'master' ]

jobs:
  quality:
    name: Build, lint, and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ '20.x' ]
        os: [ 'ubuntu-latest' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@internazionaleauto'

      - name: Clean Cache
        run: yarn cache clean --force

      - name: Install dependancy
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

  publish:
    name: Publish on NPM Registry
    if: github.ref_name == 'master'
    runs-on: ${{ matrix.os }}
    needs: [ quality ]

    permissions:
      contents: write

    strategy:
      matrix:
        node: [ '20.x' ]
        os: [ 'ubuntu-latest' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@internazionaleauto'

      - name: Install dependancy
        run: yarn install

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}